spring:
  data:
    mongodb:
      uri: ${DB_URL}
  kafka:
    bootstrap-servers: localhost:9092
topic:
  name:
    producer: vote-topic
auto:
  create:
    topics:
      enable: true
server:
  error:
    include-stacktrace: on_param

cpf-validator-url: https://user-info.herokuapp.com

